In [1]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, optimizers, Sequential, metrics

In [ ]:
def preprocess(x, y):

    x = tf.cast(x, dtype=tf.float32) / 255.
    y = tf.cast(y, dtype=tf.int32)

    return x,y

In [ ]:
(x, y), (x_val, y_val) = datasets.mnist.load_data()
print('datasets:', x.shape, y.shape, x.min(), x.max())

In [ ]:
batchsz = 128

In [ ]:
db = tf.data.Dataset.from_tensor_slices((x,y))
db = db.map(preprocess).shuffle(60000).batch(batchsz).repeat(10)

ds_val = tf.data.Dataset.from_tensor_slices((x_val, y_val))
ds_val = ds_val.map(preprocess).batch(batchsz) 

In [ ]:
x = tf.random

In [ ]:
network = Sequential([
    layers.Conv2D(6,kernel_size=3,strides=1),
    layers.MaxPooling2D(pool_size=2,strides=2),
    layers.ReLU(),
    layers.Conv2D(16,kernel_size=3,strides=1),
    layers.MaxPooling2D(pool_size=2,strides = 2),
    layers.ReLU(),
    layers.Flatten(),#打平层，方便全连接层处理
    layers.Dense(120,activation='relu'),
    layers.Dense(84,activation='relu'),
    layers.Dense(10)
])

In [ ]:
network.build(input_shape(4,28,28,1))

In [ ]:
pip install pandas

In [ ]:
pip install n

In [ ]:
from pandas import Series,DataFrame
import pandas as pd
import numpy as np

In [6]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.4943, 0.5993, 0.2405],
        [0.0974, 0.4598, 0.0127],
        [0.1233, 0.5557, 0.1176],
        [0.4487, 0.7182, 0.4081],
        [0.9130, 0.0219, 0.3259]])


In [7]:
import torch
print(torch.__version__)

print(torch.version.cuda)
print(torch.backends.cudnn.version())

1.7.0+cpu
None
None


In [17]:
batch = 5

In [18]:
n=1
m=2
p=3

In [19]:
tensor1=torch.rand((batch,n,m))
tensor2=torch.rand((batch,m,p))
out_bmm = torch.bmm(tensor1,tensor2)
    

In [21]:
tensor1

tensor([[[0.8849, 0.7723]],

        [[0.8474, 0.5947]],

        [[0.3069, 0.2837]],

        [[0.6826, 0.6710]],

        [[0.5496, 0.9686]]])

In [22]:
tensor2

tensor([[[0.4256, 0.4235, 0.5357],
         [0.8242, 0.0339, 0.4986]],

        [[0.4790, 0.2802, 0.2452],
         [0.7184, 0.7792, 0.4024]],

        [[0.2282, 0.6953, 0.1743],
         [0.8343, 0.0436, 0.0114]],

        [[0.1619, 0.5031, 0.5411],
         [0.9379, 0.3317, 0.9319]],

        [[0.2800, 0.6747, 0.4074],
         [0.6381, 0.1597, 0.5115]]])

In [20]:
out_bmm

tensor([[[1.0131, 0.4009, 0.8590]],

        [[0.8332, 0.7009, 0.4471]],

        [[0.3067, 0.2258, 0.0567]],

        [[0.7398, 0.5660, 0.9947]],

        [[0.7720, 0.5255, 0.7193]]])

In [13]:
a = tf.range(25)+1

In [14]:
a

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])>

In [15]:
#reshape 为合法维度的张量
a = tf.reshape(a,[1,5,5,1])

In [16]:
a = tf.cast(a,tf.float32)

In [17]:
#创建固定内容的卷积核矩阵
w = tf.constant([[-1,2,-3.],[4,-5,6],[-7,8,-9]])

In [18]:
w

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  2., -3.],
       [ 4., -5.,  6.],
       [-7.,  8., -9.]], dtype=float32)>

In [19]:
w_expand = tf.expand_dims(w,axis = 2)

In [20]:
w_expand

<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
array([[[-1.],
        [ 2.],
        [-3.]],

       [[ 4.],
        [-5.],
        [ 6.]],

       [[-7.],
        [ 8.],
        [-9.]]], dtype=float32)>

In [22]:
w_expand_3 = tf.expand_dims(w_expand,axis = 3)

In [23]:
w_expand_3

<tf.Tensor: shape=(3, 3, 1, 1), dtype=float32, numpy=
array([[[[-1.]],

        [[ 2.]],

        [[-3.]]],


       [[[ 4.]],

        [[-5.]],

        [[ 6.]]],


       [[[-7.]],

        [[ 8.]],

        [[-9.]]]], dtype=float32)>

In [24]:
#进行普通卷积运算，valid表示卷积核矩阵与图片矩阵完全重合的时候开始计算，因此得到的矩阵要比图片矩阵小
out = tf.nn.conv2d(a,w_expand_3,strides=2,padding = 'VALID')

In [25]:
out

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ -67.],
         [ -77.]],

        [[-117.],
         [-127.]]]], dtype=float32)>

In [26]:
a

<tf.Tensor: shape=(1, 5, 5, 1), dtype=float32, numpy=
array([[[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]],

        [[11.],
         [12.],
         [13.],
         [14.],
         [15.]],

        [[16.],
         [17.],
         [18.],
         [19.],
         [20.]],

        [[21.],
         [22.],
         [23.],
         [24.],
         [25.]]]], dtype=float32)>

In [28]:
#现在我们将卷积的输出作为转置卷积的输入，验证转置卷积的输出是否为5*5
aa = tf.nn.conv2d_transpose(out,w_expand_3,strides=2,padding='VALID',output_shape=[1,5,5,1])

In [29]:
aa

<tf.Tensor: shape=(1, 5, 5, 1), dtype=float32, numpy=
array([[[[   67.],
         [ -134.],
         [  278.],
         [ -154.],
         [  231.]],

        [[ -268.],
         [  335.],
         [ -710.],
         [  385.],
         [ -462.]],

        [[  586.],
         [ -770.],
         [ 1620.],
         [ -870.],
         [ 1074.]],

        [[ -468.],
         [  585.],
         [-1210.],
         [  635.],
         [ -762.]],

        [[  819.],
         [ -936.],
         [ 1942.],
         [-1016.],
         [ 1143.]]]], dtype=float32)>

In [30]:
a

<tf.Tensor: shape=(1, 5, 5, 1), dtype=float32, numpy=
array([[[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]],

        [[11.],
         [12.],
         [13.],
         [14.],
         [15.]],

        [[16.],
         [17.],
         [18.],
         [19.],
         [20.]],

        [[21.],
         [22.],
         [23.],
         [24.],
         [25.]]]], dtype=float32)>